# Generated by Django 5.2 on 2025-05-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_date_of_birth_user_gender_user_gender_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sexually_active',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True, verbose_name='Sexual Activity Level'),
        ),
    ]
