# Generated by Django for adding welcome_message_sent field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_sexually_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_message_sent',
            field=models.BooleanField(default=False, verbose_name='Welcome Message Sent'),
        ),
    ]
