# Generated by Django 5.2 on 2025-07-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
